import { useState, useMemo } from "preact/hooks";

/**
 * Lightweight Python syntax highlighter.
 * Returns an HTML string with <span class="syn-*"> tokens.
 */
function highlightPython(code) {
  // Order matters — earlier rules match first
  const rules = [
    // Triple-quoted strings (docstrings)
    { re: /("""[\s\S]*?"""|'''[\s\S]*?''')/g, cls: "syn-str" },
    // Single-line comments
    { re: /(#.*$)/gm, cls: "syn-comment" },
    // Strings (double then single, including f-strings)
    { re: /(f?"(?:[^"\\]|\\.)*"|f?'(?:[^'\\]|\\.)*')/g, cls: "syn-str" },
    // Decorators
    { re: /(@\w+)/g, cls: "syn-decorator" },
    // Numbers (int, float, exponential)
    { re: /\b(\d+\.?\d*(?:e[+-]?\d+)?)\b/gi, cls: "syn-num" },
    // Keywords
    { re: /\b(import|from|as|def|class|return|if|elif|else|for|in|while|with|try|except|finally|raise|pass|break|continue|and|or|not|is|lambda|yield|async|await|None|True|False|self)\b/g, cls: "syn-kw" },
    // Builtins
    { re: /\b(print|len|range|int|float|str|list|dict|tuple|set|type|isinstance|enumerate|zip|map|filter|min|max|abs|sum|sorted|super|open|hasattr|getattr)\b/g, cls: "syn-builtin" },
  ];

  // We tokenize by finding all matches, sorting by position, and building
  // the output by filling gaps with escaped plain text.
  const esc = (s) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const tokens = [];
  for (const { re, cls } of rules) {
    let m;
    re.lastIndex = 0;
    while ((m = re.exec(code)) !== null) {
      tokens.push({ start: m.index, end: m.index + m[0].length, cls, text: m[0] });
    }
  }

  // Sort by start position; resolve overlaps by keeping earlier/longer matches
  tokens.sort((a, b) => a.start - b.start || b.end - a.end);
  const merged = [];
  let lastEnd = 0;
  for (const t of tokens) {
    if (t.start < lastEnd) continue; // skip overlapping
    merged.push(t);
    lastEnd = t.end;
  }

  let html = "";
  let pos = 0;
  for (const t of merged) {
    if (t.start > pos) html += esc(code.slice(pos, t.start));
    html += `<span class="${t.cls}">${esc(t.text)}</span>`;
    pos = t.end;
  }
  if (pos < code.length) html += esc(code.slice(pos));

  return html;
}

/**
 * Generate a Python inference script based on run/project parameters.
 */
function generateInferenceScript({ taskType, backbone, numClasses, imageSize, modelPath, imagePath, device, confThreshold, classNames }) {
  const size = imageSize || 224;
  const nc = numClasses || 10;
  const dev = device || "cpu";
  const conf = confThreshold || 0.5;
  const model = modelPath || "best_model.pt";
  const img = imagePath || "image.jpg";
  const names = classNames.trim();

  const isDetection = taskType === "Object Detection";
  const isSemanticSeg = taskType === "Semantic Segmentation";
  const isInstanceSeg = taskType === "Instance Segmentation";
  const isSeg = isSemanticSeg || isInstanceSeg;
  const isMultiLabel = taskType === "Multi-Label Classification";
  const isClassification = taskType === "Classification" || isMultiLabel;

  const lines = [];

  // Header
  lines.push(`"""`);
  lines.push(`Inference script for ${taskType}`);
  lines.push(`Backbone: ${backbone}`);
  lines.push(`Generated by NightFlow`);
  lines.push(`"""`);
  lines.push(``);

  // Imports
  lines.push(`import torch`);
  lines.push(`import torch.nn.functional as F`);
  lines.push(`from PIL import Image`);
  lines.push(`from torchvision import transforms`);
  if (isDetection || isSeg) {
    lines.push(`import numpy as np`);
  }
  if (isSeg) {
    lines.push(`import matplotlib.pyplot as plt`);
    lines.push(`import matplotlib.colors as mcolors`);
  }
  if (isDetection) {
    lines.push(`import matplotlib.pyplot as plt`);
    lines.push(`import matplotlib.patches as patches`);
  }
  lines.push(``);

  // Config
  lines.push(`# ── Configuration ──`);
  lines.push(`MODEL_PATH = "${model}"`);
  lines.push(`IMAGE_PATH = "${img}"`);
  lines.push(`DEVICE = "${dev}"`);
  lines.push(`IMAGE_SIZE = ${size}`);
  lines.push(`NUM_CLASSES = ${nc}`);
  if (isDetection) {
    lines.push(`CONF_THRESHOLD = ${conf}`);
  }
  if (names) {
    lines.push(`CLASS_NAMES = [${names.split(",").map(n => `"${n.trim()}"`).join(", ")}]`);
  } else {
    lines.push(`CLASS_NAMES = [f"class_{i}" for i in range(NUM_CLASSES)]`);
  }
  lines.push(``);

  // Preprocessing
  lines.push(`# ── Preprocessing ──`);
  lines.push(`preprocess = transforms.Compose([`);
  lines.push(`    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),`);
  lines.push(`    transforms.ToTensor(),`);
  lines.push(`    transforms.Normalize(`);
  lines.push(`        mean=[0.485, 0.456, 0.406],`);
  lines.push(`        std=[0.229, 0.224, 0.225]`);
  lines.push(`    ),`);
  lines.push(`])`);
  lines.push(``);

  // Load model
  lines.push(`# ── Load Model ──`);
  lines.push(`model = torch.jit.load(MODEL_PATH, map_location=DEVICE)`);
  lines.push(`model.eval()`);
  lines.push(``);

  // Load image
  lines.push(`# ── Load Image ──`);
  lines.push(`image = Image.open(IMAGE_PATH).convert("RGB")`);
  if (isDetection || isSeg) {
    lines.push(`original_size = image.size  # (W, H)`);
  }
  lines.push(`input_tensor = preprocess(image).unsqueeze(0).to(DEVICE)`);
  lines.push(``);

  // Inference
  lines.push(`# ── Inference ──`);
  lines.push(`with torch.no_grad():`);
  lines.push(`    output = model(input_tensor)`);
  lines.push(``);

  // Post-processing based on task type
  if (isClassification && !isMultiLabel) {
    lines.push(`# ── Post-processing (Classification) ──`);
    lines.push(`probabilities = F.softmax(output, dim=1)`);
    lines.push(`confidence, predicted_idx = torch.max(probabilities, dim=1)`);
    lines.push(`predicted_class = CLASS_NAMES[predicted_idx.item()]`);
    lines.push(``);
    lines.push(`print(f"Predicted: {predicted_class}")`);
    lines.push(`print(f"Confidence: {confidence.item():.4f}")`);
    lines.push(``);
    lines.push(`# Top-5 predictions`);
    lines.push(`top5_probs, top5_indices = torch.topk(probabilities, min(5, NUM_CLASSES))`);
    lines.push(`print("\\nTop-5 predictions:")`);
    lines.push(`for prob, idx in zip(top5_probs[0], top5_indices[0]):`);
    lines.push(`    print(f"  {CLASS_NAMES[idx.item()]:>20s}: {prob.item():.4f}")`);
  } else if (isMultiLabel) {
    lines.push(`# ── Post-processing (Multi-Label Classification) ──`);
    lines.push(`probabilities = torch.sigmoid(output)`);
    lines.push(`predicted = (probabilities > ${conf}).int()`);
    lines.push(``);
    lines.push(`print("Predicted labels:")`);
    lines.push(`for i, (pred, prob) in enumerate(zip(predicted[0], probabilities[0])):`);
    lines.push(`    if pred.item() == 1:`);
    lines.push(`        print(f"  {CLASS_NAMES[i]}: {prob.item():.4f}")`);
  } else if (isDetection) {
    lines.push(`# ── Post-processing (Object Detection) ──`);
    lines.push(`# Output format depends on your model export.`);
    lines.push(`# Typical TorchScript detection output: list of dicts with`);
    lines.push(`# 'boxes' (N,4), 'labels' (N,), 'scores' (N,)`);
    lines.push(`if isinstance(output, dict):`);
    lines.push(`    boxes = output["boxes"]`);
    lines.push(`    scores = output["scores"]`);
    lines.push(`    labels = output["labels"]`);
    lines.push(`elif isinstance(output, (list, tuple)) and len(output) > 0:`);
    lines.push(`    result = output[0] if isinstance(output[0], dict) else {"boxes": output[0], "scores": output[1], "labels": output[2]}`);
    lines.push(`    boxes = result["boxes"]`);
    lines.push(`    scores = result["scores"]`);
    lines.push(`    labels = result["labels"]`);
    lines.push(`else:`);
    lines.push(`    boxes, scores, labels = output[..., :4], output[..., 4], output[..., 5].int()`);
    lines.push(``);
    lines.push(`# Filter by confidence`);
    lines.push(`keep = scores > CONF_THRESHOLD`);
    lines.push(`boxes = boxes[keep]`);
    lines.push(`scores = scores[keep]`);
    lines.push(`labels = labels[keep]`);
    lines.push(``);
    lines.push(`# Scale boxes back to original image size`);
    lines.push(`w_scale = original_size[0] / IMAGE_SIZE`);
    lines.push(`h_scale = original_size[1] / IMAGE_SIZE`);
    lines.push(`boxes[:, [0, 2]] *= w_scale`);
    lines.push(`boxes[:, [1, 3]] *= h_scale`);
    lines.push(``);
    lines.push(`print(f"Detected {len(boxes)} objects:")`);
    lines.push(`for box, score, label in zip(boxes, scores, labels):`);
    lines.push(`    cls_name = CLASS_NAMES[label.item()] if label.item() < len(CLASS_NAMES) else f"class_{label.item()}"`);
    lines.push(`    print(f"  {cls_name}: {score.item():.3f} at [{box[0]:.0f}, {box[1]:.0f}, {box[2]:.0f}, {box[3]:.0f}]")`);
    lines.push(``);
    lines.push(`# ── Visualize ──`);
    lines.push(`fig, ax = plt.subplots(1, figsize=(12, 8))`);
    lines.push(`ax.imshow(image)`);
    lines.push(`colors = plt.cm.Set3(np.linspace(0, 1, NUM_CLASSES))`);
    lines.push(`for box, score, label in zip(boxes, scores, labels):`);
    lines.push(`    x1, y1, x2, y2 = box.cpu().numpy()`);
    lines.push(`    cls_name = CLASS_NAMES[label.item()] if label.item() < len(CLASS_NAMES) else f"class_{label.item()}"`);
    lines.push(`    color = colors[label.item() % len(colors)]`);
    lines.push(`    rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1, linewidth=2, edgecolor=color, facecolor="none")`);
    lines.push(`    ax.add_patch(rect)`);
    lines.push(`    ax.text(x1, y1 - 5, f"{cls_name} {score.item():.2f}", color=color, fontsize=10, weight="bold")`);
    lines.push(`ax.set_axis_off()`);
    lines.push(`plt.tight_layout()`);
    lines.push(`plt.savefig("detection_result.png", dpi=150, bbox_inches="tight")`);
    lines.push(`print("Saved visualization to detection_result.png")`);
  } else if (isSemanticSeg) {
    lines.push(`# ── Post-processing (Semantic Segmentation) ──`);
    lines.push(`# output shape: (1, num_classes, H, W)`);
    lines.push(`pred_mask = output.argmax(dim=1).squeeze(0).cpu().numpy()  # (H, W)`);
    lines.push(``);
    lines.push(`# Resize mask back to original image size`);
    lines.push(`from PIL import Image as PILImage`);
    lines.push(`pred_mask_resized = np.array(PILImage.fromarray(pred_mask.astype(np.uint8)).resize(original_size, PILImage.NEAREST))`);
    lines.push(``);
    lines.push(`unique_classes = np.unique(pred_mask_resized)`);
    lines.push(`print(f"Detected {len(unique_classes)} classes: {[CLASS_NAMES[c] if c < len(CLASS_NAMES) else f'class_{c}' for c in unique_classes]}")`);
    lines.push(``);
    lines.push(`# ── Visualize ──`);
    lines.push(`cmap = plt.cm.get_cmap("tab20", NUM_CLASSES)`);
    lines.push(`fig, axes = plt.subplots(1, 3, figsize=(18, 6))`);
    lines.push(`axes[0].imshow(image)`);
    lines.push(`axes[0].set_title("Input Image")`);
    lines.push(`axes[1].imshow(pred_mask_resized, cmap=cmap, vmin=0, vmax=NUM_CLASSES - 1)`);
    lines.push(`axes[1].set_title("Prediction Mask")`);
    lines.push(`axes[2].imshow(image)`);
    lines.push(`axes[2].imshow(pred_mask_resized, cmap=cmap, alpha=0.5, vmin=0, vmax=NUM_CLASSES - 1)`);
    lines.push(`axes[2].set_title("Overlay")`);
    lines.push(`for ax in axes: ax.set_axis_off()`);
    lines.push(`plt.tight_layout()`);
    lines.push(`plt.savefig("segmentation_result.png", dpi=150, bbox_inches="tight")`);
    lines.push(`print("Saved visualization to segmentation_result.png")`);
  } else if (isInstanceSeg) {
    lines.push(`# ── Post-processing (Instance Segmentation) ──`);
    lines.push(`# Typical output: list of dicts with 'boxes', 'labels', 'scores', 'masks'`);
    lines.push(`if isinstance(output, (list, tuple)):`);
    lines.push(`    result = output[0]`);
    lines.push(`else:`);
    lines.push(`    result = output`);
    lines.push(``);
    lines.push(`boxes = result["boxes"]`);
    lines.push(`scores = result["scores"]`);
    lines.push(`labels = result["labels"]`);
    lines.push(`masks = result["masks"]  # (N, 1, H, W)`);
    lines.push(``);
    lines.push(`keep = scores > ${conf}`);
    lines.push(`boxes = boxes[keep]`);
    lines.push(`scores = scores[keep]`);
    lines.push(`labels = labels[keep]`);
    lines.push(`masks = masks[keep]`);
    lines.push(``);
    lines.push(`print(f"Detected {len(boxes)} instances:")`);
    lines.push(`for score, label in zip(scores, labels):`);
    lines.push(`    cls_name = CLASS_NAMES[label.item()] if label.item() < len(CLASS_NAMES) else f"class_{label.item()}"`);
    lines.push(`    print(f"  {cls_name}: {score.item():.3f}")`);
    lines.push(``);
    lines.push(`# ── Visualize ──`);
    lines.push(`fig, ax = plt.subplots(1, figsize=(12, 8))`);
    lines.push(`ax.imshow(image)`);
    lines.push(`colors = plt.cm.Set3(np.linspace(0, 1, max(len(boxes), 1)))`);
    lines.push(`for i, (mask, score, label) in enumerate(zip(masks, scores, labels)):`);
    lines.push(`    m = mask[0].cpu().numpy() > 0.5`);
    lines.push(`    colored = np.zeros((*m.shape, 4))`);
    lines.push(`    colored[m] = colors[i]`);
    lines.push(`    colored[m, 3] = 0.5`);
    lines.push(`    ax.imshow(colored)`);
    lines.push(`ax.set_axis_off()`);
    lines.push(`plt.tight_layout()`);
    lines.push(`plt.savefig("instance_result.png", dpi=150, bbox_inches="tight")`);
    lines.push(`print("Saved visualization to instance_result.png")`);
  }

  return lines.join("\n");
}

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <button class="inference-copy-btn" onClick={handleCopy}>
      {copied ? (
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="20 6 9 17 4 12" />
        </svg>
      ) : (
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
        </svg>
      )}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

export function InferenceTab({ run, project }) {
  const taskType = run.taskType || project?.taskType || "Classification";
  const backbone = run.backbone || run.model || "efficientnet_b0";
  const hp = { ...(run.hyperparameters || {}), ...(run.fileHparams || {}) };
  const defaultSize = hp.image_size || hp.imageSize || 224;
  const defaultClasses = hp.num_classes || hp.numClasses || project?.numClasses || 10;

  const isDetection = taskType === "Object Detection" || taskType === "Instance Segmentation";
  const isMultiLabel = taskType === "Multi-Label Classification";

  const [modelPath, setModelPath] = useState(`${(run.name || run.id)}.pt`);
  const [imagePath, setImagePath] = useState("image.jpg");
  const [device, setDevice] = useState("cuda");
  const [imageSize, setImageSize] = useState(String(defaultSize));
  const [numClasses, setNumClasses] = useState(String(defaultClasses));
  const [confThreshold, setConfThreshold] = useState("0.5");
  const [classNames, setClassNames] = useState("");

  const script = generateInferenceScript({
    taskType,
    backbone,
    numClasses: numClasses || defaultClasses,
    imageSize: imageSize || defaultSize,
    modelPath,
    imagePath,
    device,
    confThreshold: parseFloat(confThreshold) || 0.5,
    classNames,
  });

  const highlighted = useMemo(() => highlightPython(script), [script]);

  return (
    <div class="inference-tab">
      <div class="inference-params">
        <h3 class="inference-params-title">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="opacity:0.5">
            <polyline points="16 18 22 12 16 6" />
            <polyline points="8 6 2 12 8 18" />
          </svg>
          Script Parameters
        </h3>
        <div class="inference-params-grid">
          <label class="inference-field">
            <span>Model Path</span>
            <input type="text" value={modelPath} onInput={(e) => setModelPath(e.currentTarget.value)} placeholder="best_model.pt" />
          </label>
          <label class="inference-field">
            <span>Image Path</span>
            <input type="text" value={imagePath} onInput={(e) => setImagePath(e.currentTarget.value)} placeholder="image.jpg" />
          </label>
          <label class="inference-field">
            <span>Device</span>
            <select value={device} onChange={(e) => setDevice(e.currentTarget.value)}>
              <option value="cuda">CUDA (GPU)</option>
              <option value="cpu">CPU</option>
              <option value="mps">MPS (Apple Silicon)</option>
            </select>
          </label>
          <label class="inference-field">
            <span>Image Size</span>
            <input type="number" value={imageSize} onInput={(e) => setImageSize(e.currentTarget.value)} min="32" max="1024" />
          </label>
          <label class="inference-field">
            <span>Num Classes</span>
            <input type="number" value={numClasses} onInput={(e) => setNumClasses(e.currentTarget.value)} min="2" />
          </label>
          {(isDetection || isMultiLabel) && (
            <label class="inference-field">
              <span>{isDetection ? "Confidence Threshold" : "Sigmoid Threshold"}</span>
              <input type="number" value={confThreshold} onInput={(e) => setConfThreshold(e.currentTarget.value)} min="0" max="1" step="0.05" />
            </label>
          )}
          <label class="inference-field inference-field-wide">
            <span>Class Names (comma-separated, optional)</span>
            <input type="text" value={classNames} onInput={(e) => setClassNames(e.currentTarget.value)} placeholder="cat, dog, bird, ..." />
          </label>
        </div>
      </div>

      <div class="inference-script-container">
        <div class="inference-script-header">
          <span class="inference-script-filename">inference.py</span>
          <CopyButton text={script} />
        </div>
        <pre class="inference-script-code"><code dangerouslySetInnerHTML={{ __html: highlighted }} /></pre>
      </div>
    </div>
  );
}
