import { useState, useMemo, useEffect } from "preact/hooks";
import { invoke } from "@tauri-apps/api/core";
import { notify } from "../utils/notifications.js";
import { platform } from "../state/dashboard.js";

/**
 * Lightweight Python syntax highlighter.
 * Returns an HTML string with <span class="syn-*"> tokens.
 */
function highlightPython(code) {
  // Order matters — earlier rules match first
  const rules = [
    // Triple-quoted strings (docstrings)
    { re: /("""[\s\S]*?"""|'''[\s\S]*?''')/g, cls: "syn-str" },
    // Single-line comments
    { re: /(#.*$)/gm, cls: "syn-comment" },
    // Strings (double then single, including f-strings)
    { re: /(f?"(?:[^"\\]|\\.)*"|f?'(?:[^'\\]|\\.)*')/g, cls: "syn-str" },
    // Decorators
    { re: /(@\w+)/g, cls: "syn-decorator" },
    // Numbers (int, float, exponential)
    { re: /\b(\d+\.?\d*(?:e[+-]?\d+)?)\b/gi, cls: "syn-num" },
    // Keywords
    { re: /\b(import|from|as|def|class|return|if|elif|else|for|in|while|with|try|except|finally|raise|pass|break|continue|and|or|not|is|lambda|yield|async|await|None|True|False|self)\b/g, cls: "syn-kw" },
    // Builtins
    { re: /\b(print|len|range|int|float|str|list|dict|tuple|set|type|isinstance|enumerate|zip|map|filter|min|max|abs|sum|sorted|super|open|hasattr|getattr)\b/g, cls: "syn-builtin" },
  ];

  // We tokenize by finding all matches, sorting by position, and building
  // the output by filling gaps with escaped plain text.
  const esc = (s) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const tokens = [];
  for (const { re, cls } of rules) {
    let m;
    re.lastIndex = 0;
    while ((m = re.exec(code)) !== null) {
      tokens.push({ start: m.index, end: m.index + m[0].length, cls, text: m[0] });
    }
  }

  // Sort by start position; resolve overlaps by keeping earlier/longer matches
  tokens.sort((a, b) => a.start - b.start || b.end - a.end);
  const merged = [];
  let lastEnd = 0;
  for (const t of tokens) {
    if (t.start < lastEnd) continue; // skip overlapping
    merged.push(t);
    lastEnd = t.end;
  }

  let html = "";
  let pos = 0;
  for (const t of merged) {
    if (t.start > pos) html += esc(code.slice(pos, t.start));
    html += `<span class="${t.cls}">${esc(t.text)}</span>`;
    pos = t.end;
  }
  if (pos < code.length) html += esc(code.slice(pos));

  return html;
}

/**
 * Generate a Python inference script based on run/project parameters.
 */
function generateInferenceScript({ taskType, backbone, numClasses, imageSize, modelPath, imagePath, device, confThreshold, classNames, exportFormat }) {
  const size = imageSize || 224;
  const nc = numClasses || 10;
  const dev = device || "cpu";
  const conf = confThreshold || 0.5;
  const model = modelPath || "best_model.pt";
  const img = imagePath || "image.jpg";
  const names = classNames.trim();
  const format = exportFormat || "torchscript";

  const isDetection = taskType === "Object Detection";
  const isSemanticSeg = taskType === "Semantic Segmentation";
  const isInstanceSeg = taskType === "Instance Segmentation";
  const isSeg = isSemanticSeg || isInstanceSeg;
  const isMultiLabel = taskType === "Multi-Label Classification";
  const isClassification = taskType === "Classification" || isMultiLabel;

  const isOnnx = format === "onnx";
  const isTensorRT = format === "tensorrt";

  const lines = [];
  // helper to push indented lines inside main()
  const I = (s) => `    ${s}`;

  // Header
  lines.push(`"""`);
  lines.push(`Inference script for ${taskType}`);
  lines.push(`Backbone: ${backbone}`);
  lines.push(`Format: ${format === "torchscript" ? "TorchScript" : format === "onnx" ? "ONNX Runtime" : "TensorRT"}`);
  lines.push(`Generated by NightFlow`);
  lines.push(`"""`);
  lines.push(``);

  // Imports
  lines.push(`from dataclasses import dataclass`);
  if (isTensorRT) {
    lines.push(`import tensorrt as trt`);
    lines.push(`import pycuda.driver as cuda`);
    lines.push(`import pycuda.autoinit`);
  } else if (isOnnx) {
    lines.push(`import onnxruntime as ort`);
  } else {
    lines.push(`import torch`);
    lines.push(`import torch.nn.functional as F`);
  }
  lines.push(`import numpy as np`);
  lines.push(`from PIL import Image`);
  if (!isOnnx && !isTensorRT) {
    lines.push(`from torchvision import transforms`);
  }
  if (isSeg) {
    lines.push(`import matplotlib.pyplot as plt`);
    lines.push(`import matplotlib.colors as mcolors`);
  }
  if (isDetection) {
    lines.push(`import matplotlib.pyplot as plt`);
    lines.push(`import matplotlib.patches as patches`);
  }
  lines.push(``);
  lines.push(``);

  // Config dataclass
  lines.push(`# ── Configuration ──`);
  lines.push(`# Edit these defaults or pass overrides when constructing Config.`);
  lines.push(``);
  lines.push(``);
  lines.push(`@dataclass`);
  lines.push(`class Config:`);
  lines.push(`    """Inference configuration — modify defaults below or override at runtime."""`);
  lines.push(``);
  lines.push(`    model_path: str = "${model}"`);
  lines.push(`    image_path: str = "${img}"`);
  if (!isOnnx && !isTensorRT) {
    lines.push(`    device: str = "${dev}"`);
  }
  lines.push(`    image_size: int = ${size}`);
  lines.push(`    num_classes: int = ${nc}`);
  if (isDetection || isInstanceSeg || isMultiLabel) {
    lines.push(`    conf_threshold: float = ${conf}`);
  }
  if (names) {
    lines.push(`    class_names: tuple = (${names.split(",").map(n => `"${n.trim()}"`).join(", ")},)`);
  } else {
    lines.push(`    class_names: tuple = None`);
  }
  lines.push(``);
  if (!names) {
    lines.push(`    def __post_init__(self):`);
    lines.push(`        if self.class_names is None:`);
    lines.push(`            self.class_names = tuple(f"class_{i}" for i in range(self.num_classes))`);
    lines.push(``);
  }

  // Preprocessing function
  if (isOnnx || isTensorRT) {
    lines.push(``);
    lines.push(`# ── Preprocessing ──`);
    lines.push(`# Resize, normalize with ImageNet stats, and convert HWC -> NCHW.`);
    lines.push(``);
    lines.push(``);
    lines.push(`def preprocess(image_path: str, image_size: int) -> np.ndarray:`);
    lines.push(`    """Load an image, resize, normalize, and return as NCHW float32 array."""`);
    lines.push(`    image = Image.open(image_path).convert("RGB")`);
    lines.push(`    image = image.resize((image_size, image_size))`);
    lines.push(`    img_array = np.array(image).astype(np.float32) / 255.0`);
    lines.push(`    mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)`);
    lines.push(`    std = np.array([0.229, 0.224, 0.225], dtype=np.float32)`);
    lines.push(`    img_array = (img_array - mean) / std`);
    lines.push(`    img_array = np.transpose(img_array, (2, 0, 1))[np.newaxis, ...]`);
    lines.push(`    return img_array.astype(np.float32)`);
    lines.push(``);
  }

  // TensorRT helper
  if (isTensorRT) {
    lines.push(``);
    lines.push(`# ── TensorRT Buffer Allocation ──`);
    lines.push(``);
    lines.push(``);
    lines.push(`def allocate_buffers(engine):`);
    lines.push(`    """Allocate host and device buffers for all engine I/O tensors."""`);
    lines.push(`    inputs, outputs, bindings = [], [], []`);
    lines.push(`    stream = cuda.Stream()`);
    lines.push(`    for i in range(engine.num_io_tensors):`);
    lines.push(`        name = engine.get_tensor_name(i)`);
    lines.push(`        dtype = trt.nptype(engine.get_tensor_dtype(name))`);
    lines.push(`        shape = engine.get_tensor_shape(name)`);
    lines.push(`        size = trt.volume(shape)`);
    lines.push(`        host_mem = cuda.pagelocked_empty(size, dtype)`);
    lines.push(`        device_mem = cuda.mem_alloc(host_mem.nbytes)`);
    lines.push(`        bindings.append(int(device_mem))`);
    lines.push(`        if engine.get_tensor_mode(name) == trt.TensorIOMode.INPUT:`);
    lines.push(`            inputs.append({"host": host_mem, "device": device_mem, "name": name})`);
    lines.push(`        else:`);
    lines.push(`            outputs.append({"host": host_mem, "device": device_mem, "name": name, "shape": shape})`);
    lines.push(`    return inputs, outputs, bindings, stream`);
    lines.push(``);
  }

  // main function
  lines.push(``);
  lines.push(`# ── Main ──`);
  lines.push(``);
  lines.push(``);
  lines.push(`def main(cfg: Config):`);
  lines.push(I(`"""Run inference with the given configuration."""`));

  // Preprocessing (torchscript only — onnx/trt use the standalone function)
  if (!isOnnx && !isTensorRT) {
    lines.push(I(`# Preprocessing: resize, convert to tensor, normalize with ImageNet stats`));
    lines.push(I(`transform = transforms.Compose([`));
    lines.push(I(`    transforms.Resize((cfg.image_size, cfg.image_size)),`));
    lines.push(I(`    transforms.ToTensor(),`));
    lines.push(I(`    transforms.Normalize(`));
    lines.push(I(`        mean=[0.485, 0.456, 0.406],`));
    lines.push(I(`        std=[0.229, 0.224, 0.225]`));
    lines.push(I(`    ),`));
    lines.push(I(`])`));
    lines.push(``);
  }

  // Load model
  if (isTensorRT) {
    lines.push(I(`# Load TensorRT engine`));
    lines.push(I(`logger = trt.Logger(trt.Logger.WARNING)`));
    lines.push(I(`runtime = trt.Runtime(logger)`));
    lines.push(I(`with open(cfg.model_path, "rb") as f:`));
    lines.push(I(`    engine = runtime.deserialize_cuda_engine(f.read())`));
    lines.push(I(`context = engine.create_execution_context()`));
    lines.push(I(`inputs, outputs, bindings, stream = allocate_buffers(engine)`));
    lines.push(``);
  } else if (isOnnx) {
    lines.push(I(`# Load ONNX model`));
    lines.push(I(`providers = [`));
    if (dev === "cuda") {
      lines.push(I(`    "CUDAExecutionProvider",`));
    } else if (dev === "mps") {
      lines.push(I(`    "CoreMLExecutionProvider",`));
    } else if (dev === "directml") {
      lines.push(I(`    "DmlExecutionProvider",`));
    }
    lines.push(I(`    "CPUExecutionProvider",`));
    lines.push(I(`]`));
    lines.push(I(`session = ort.InferenceSession(cfg.model_path, providers=providers)`));
    lines.push(I(`input_name = session.get_inputs()[0].name`));
    lines.push(``);
  } else {
    lines.push(I(`# Load model`));
    lines.push(I(`model = torch.jit.load(cfg.model_path, map_location=cfg.device)`));
    lines.push(I(`model.eval()`));
    lines.push(``);
  }

  // Load image & inference
  if (isTensorRT) {
    lines.push(I(`# Load image & run inference`));
    lines.push(I(`image = Image.open(cfg.image_path).convert("RGB")`));
    if (isDetection || isSeg) {
      lines.push(I(`original_size = image.size  # (W, H)`));
    }
    lines.push(I(`input_data = preprocess(cfg.image_path, cfg.image_size)`));
    lines.push(``);
    lines.push(I(`np.copyto(inputs[0]["host"], input_data.ravel())`));
    lines.push(I(`cuda.memcpy_htod_async(inputs[0]["device"], inputs[0]["host"], stream)`));
    lines.push(I(`for inp in inputs:`));
    lines.push(I(`    context.set_tensor_address(inp["name"], int(inp["device"]))`));
    lines.push(I(`for out in outputs:`));
    lines.push(I(`    context.set_tensor_address(out["name"], int(out["device"]))`));
    lines.push(I(`context.execute_async_v3(stream_handle=stream.handle)`));
    lines.push(I(`for out in outputs:`));
    lines.push(I(`    cuda.memcpy_dtoh_async(out["host"], out["device"], stream)`));
    lines.push(I(`stream.synchronize()`));
    lines.push(``);
    lines.push(I(`output = outputs[0]["host"].reshape(outputs[0]["shape"])`));
    lines.push(``);
  } else if (isOnnx) {
    lines.push(I(`# Load image & run inference`));
    lines.push(I(`image = Image.open(cfg.image_path).convert("RGB")`));
    if (isDetection || isSeg) {
      lines.push(I(`original_size = image.size  # (W, H)`));
    }
    lines.push(I(`input_data = preprocess(cfg.image_path, cfg.image_size)`));
    lines.push(I(`output = session.run(None, {input_name: input_data})[0]`));
    lines.push(``);
  } else {
    lines.push(I(`# Load image & run inference`));
    lines.push(I(`image = Image.open(cfg.image_path).convert("RGB")`));
    if (isDetection || isSeg) {
      lines.push(I(`original_size = image.size  # (W, H)`));
    }
    lines.push(I(`input_tensor = transform(image).unsqueeze(0).to(cfg.device)`));
    lines.push(``);
    lines.push(I(`with torch.no_grad():`));
    lines.push(I(`    output = model(input_tensor)`));
    lines.push(``);
  }

  // Post-processing
  if (isClassification && !isMultiLabel) {
    if (isOnnx || isTensorRT) {
      lines.push(I(`# Post-processing (Classification)`));
      lines.push(I(`exp_output = np.exp(output - np.max(output, axis=1, keepdims=True))`));
      lines.push(I(`probabilities = exp_output / np.sum(exp_output, axis=1, keepdims=True)`));
      lines.push(I(`predicted_idx = np.argmax(probabilities, axis=1)[0]`));
      lines.push(I(`confidence = probabilities[0, predicted_idx]`));
      lines.push(I(`predicted_class = cfg.class_names[predicted_idx]`));
      lines.push(``);
      lines.push(I(`print(f"Predicted: {predicted_class}")`));
      lines.push(I(`print(f"Confidence: {confidence:.4f}")`));
      lines.push(``);
      lines.push(I(`top5_indices = np.argsort(probabilities[0])[::-1][:min(5, cfg.num_classes)]`));
      lines.push(I(`print("\\nTop-5 predictions:")`));
      lines.push(I(`for idx in top5_indices:`));
      lines.push(I(`    print(f"  {cfg.class_names[idx]:>20s}: {probabilities[0, idx]:.4f}")`));
    } else {
      lines.push(I(`# Post-processing (Classification)`));
      lines.push(I(`probabilities = F.softmax(output, dim=1)`));
      lines.push(I(`confidence, predicted_idx = torch.max(probabilities, dim=1)`));
      lines.push(I(`predicted_class = cfg.class_names[predicted_idx.item()]`));
      lines.push(``);
      lines.push(I(`print(f"Predicted: {predicted_class}")`));
      lines.push(I(`print(f"Confidence: {confidence.item():.4f}")`));
      lines.push(``);
      lines.push(I(`top5_probs, top5_indices = torch.topk(probabilities, min(5, cfg.num_classes))`));
      lines.push(I(`print("\\nTop-5 predictions:")`));
      lines.push(I(`for prob, idx in zip(top5_probs[0], top5_indices[0]):`));
      lines.push(I(`    print(f"  {cfg.class_names[idx.item()]:>20s}: {prob.item():.4f}")`));
    }
  } else if (isMultiLabel) {
    if (isOnnx || isTensorRT) {
      lines.push(I(`# Post-processing (Multi-Label Classification)`));
      lines.push(I(`probabilities = 1.0 / (1.0 + np.exp(-output))  # sigmoid`));
      lines.push(I(`predicted = (probabilities > cfg.conf_threshold).astype(int)`));
      lines.push(``);
      lines.push(I(`print("Predicted labels:")`));
      lines.push(I(`for i, (pred, prob) in enumerate(zip(predicted[0], probabilities[0])):`));
      lines.push(I(`    if pred == 1:`));
      lines.push(I(`        print(f"  {cfg.class_names[i]}: {prob:.4f}")`));
    } else {
      lines.push(I(`# Post-processing (Multi-Label Classification)`));
      lines.push(I(`probabilities = torch.sigmoid(output)`));
      lines.push(I(`predicted = (probabilities > cfg.conf_threshold).int()`));
      lines.push(``);
      lines.push(I(`print("Predicted labels:")`));
      lines.push(I(`for i, (pred, prob) in enumerate(zip(predicted[0], probabilities[0])):`));
      lines.push(I(`    if pred.item() == 1:`));
      lines.push(I(`        print(f"  {cfg.class_names[i]}: {prob.item():.4f}")`));
    }
  } else if (isDetection) {
    if (isOnnx || isTensorRT) {
      lines.push(I(`# Post-processing (Object Detection)`));
      lines.push(I(`if output.ndim == 3:`));
      lines.push(I(`    output = output[0]`));
      lines.push(I(`boxes = output[:, :4]`));
      lines.push(I(`scores = output[:, 4]`));
      lines.push(I(`labels = output[:, 5].astype(int)`));
      lines.push(``);
      lines.push(I(`keep = scores > cfg.conf_threshold`));
      lines.push(I(`boxes, scores, labels = boxes[keep], scores[keep], labels[keep]`));
    } else {
      lines.push(I(`# Post-processing (Object Detection)`));
      lines.push(I(`if isinstance(output, dict):`));
      lines.push(I(`    boxes, scores, labels = output["boxes"], output["scores"], output["labels"]`));
      lines.push(I(`elif isinstance(output, (list, tuple)) and len(output) > 0:`));
      lines.push(I(`    result = output[0] if isinstance(output[0], dict) else {"boxes": output[0], "scores": output[1], "labels": output[2]}`));
      lines.push(I(`    boxes, scores, labels = result["boxes"], result["scores"], result["labels"]`));
      lines.push(I(`else:`));
      lines.push(I(`    boxes, scores, labels = output[..., :4], output[..., 4], output[..., 5].int()`));
      lines.push(``);
      lines.push(I(`keep = scores > cfg.conf_threshold`));
      lines.push(I(`boxes, scores, labels = boxes[keep], scores[keep], labels[keep]`));
    }
    lines.push(``);
    lines.push(I(`# Scale boxes to original image size`));
    lines.push(I(`w_scale = original_size[0] / cfg.image_size`));
    lines.push(I(`h_scale = original_size[1] / cfg.image_size`));
    lines.push(I(`boxes[:, [0, 2]] *= w_scale`));
    lines.push(I(`boxes[:, [1, 3]] *= h_scale`));
    lines.push(``);
    lines.push(I(`print(f"Detected {len(boxes)} objects:")`));
    lines.push(I(`for box, score, label in zip(boxes, scores, labels):`));
    if (isOnnx || isTensorRT) {
      lines.push(I(`    cls_name = cfg.class_names[label] if label < len(cfg.class_names) else f"class_{label}"`));
      lines.push(I(`    print(f"  {cls_name}: {score:.3f} at [{box[0]:.0f}, {box[1]:.0f}, {box[2]:.0f}, {box[3]:.0f}]")`));
    } else {
      lines.push(I(`    cls_name = cfg.class_names[label.item()] if label.item() < len(cfg.class_names) else f"class_{label.item()}"`));
      lines.push(I(`    print(f"  {cls_name}: {score.item():.3f} at [{box[0]:.0f}, {box[1]:.0f}, {box[2]:.0f}, {box[3]:.0f}]")`));
    }
    lines.push(``);
    lines.push(I(`# Visualize`));
    lines.push(I(`fig, ax = plt.subplots(1, figsize=(12, 8))`));
    lines.push(I(`ax.imshow(image)`));
    lines.push(I(`colors = plt.cm.Set3(np.linspace(0, 1, cfg.num_classes))`));
    lines.push(I(`for box, score, label in zip(boxes, scores, labels):`));
    if (isOnnx || isTensorRT) {
      lines.push(I(`    x1, y1, x2, y2 = box`));
      lines.push(I(`    cls_name = cfg.class_names[label] if label < len(cfg.class_names) else f"class_{label}"`));
      lines.push(I(`    color = colors[label % len(colors)]`));
    } else {
      lines.push(I(`    x1, y1, x2, y2 = box.cpu().numpy()`));
      lines.push(I(`    cls_name = cfg.class_names[label.item()] if label.item() < len(cfg.class_names) else f"class_{label.item()}"`));
      lines.push(I(`    color = colors[label.item() % len(colors)]`));
    }
    lines.push(I(`    rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1, linewidth=2, edgecolor=color, facecolor="none")`));
    lines.push(I(`    ax.add_patch(rect)`));
    if (isOnnx || isTensorRT) {
      lines.push(I(`    ax.text(x1, y1 - 5, f"{cls_name} {score:.2f}", color=color, fontsize=10, weight="bold")`));
    } else {
      lines.push(I(`    ax.text(x1, y1 - 5, f"{cls_name} {score.item():.2f}", color=color, fontsize=10, weight="bold")`));
    }
    lines.push(I(`ax.set_axis_off()`));
    lines.push(I(`plt.tight_layout()`));
    lines.push(I(`plt.savefig("detection_result.png", dpi=150, bbox_inches="tight")`));
    lines.push(I(`print("Saved visualization to detection_result.png")`));
  } else if (isSemanticSeg) {
    if (isOnnx || isTensorRT) {
      lines.push(I(`# Post-processing (Semantic Segmentation)`));
      lines.push(I(`pred_mask = np.argmax(output, axis=1).squeeze(0)`));
    } else {
      lines.push(I(`# Post-processing (Semantic Segmentation)`));
      lines.push(I(`pred_mask = output.argmax(dim=1).squeeze(0).cpu().numpy()`));
    }
    lines.push(``);
    lines.push(I(`pred_mask_resized = np.array(Image.fromarray(pred_mask.astype(np.uint8)).resize(original_size, Image.NEAREST))`));
    lines.push(``);
    lines.push(I(`unique_classes = np.unique(pred_mask_resized)`));
    lines.push(I(`print(f"Detected {len(unique_classes)} classes: {[cfg.class_names[c] if c < len(cfg.class_names) else f'class_{c}' for c in unique_classes]}")`));
    lines.push(``);
    lines.push(I(`cmap = plt.cm.get_cmap("tab20", cfg.num_classes)`));
    lines.push(I(`fig, axes = plt.subplots(1, 3, figsize=(18, 6))`));
    lines.push(I(`axes[0].imshow(image)`));
    lines.push(I(`axes[0].set_title("Input Image")`));
    lines.push(I(`axes[1].imshow(pred_mask_resized, cmap=cmap, vmin=0, vmax=cfg.num_classes - 1)`));
    lines.push(I(`axes[1].set_title("Prediction Mask")`));
    lines.push(I(`axes[2].imshow(image)`));
    lines.push(I(`axes[2].imshow(pred_mask_resized, cmap=cmap, alpha=0.5, vmin=0, vmax=cfg.num_classes - 1)`));
    lines.push(I(`axes[2].set_title("Overlay")`));
    lines.push(I(`for ax in axes: ax.set_axis_off()`));
    lines.push(I(`plt.tight_layout()`));
    lines.push(I(`plt.savefig("segmentation_result.png", dpi=150, bbox_inches="tight")`));
    lines.push(I(`print("Saved visualization to segmentation_result.png")`));
  } else if (isInstanceSeg) {
    if (isOnnx || isTensorRT) {
      lines.push(I(`# Post-processing (Instance Segmentation)`));
      lines.push(I(`boxes = output[:, :4]`));
      lines.push(I(`scores = output[:, 4]`));
      lines.push(I(`labels = output[:, 5].astype(int)`));
      lines.push(``);
      lines.push(I(`keep = scores > cfg.conf_threshold`));
      lines.push(I(`boxes, scores, labels = boxes[keep], scores[keep], labels[keep]`));
      lines.push(``);
      lines.push(I(`print(f"Detected {len(boxes)} instances:")`));
      lines.push(I(`for score, label in zip(scores, labels):`));
      lines.push(I(`    cls_name = cfg.class_names[label] if label < len(cfg.class_names) else f"class_{label}"`));
      lines.push(I(`    print(f"  {cls_name}: {score:.3f}")`));
    } else {
      lines.push(I(`# Post-processing (Instance Segmentation)`));
      lines.push(I(`if isinstance(output, (list, tuple)):`));
      lines.push(I(`    result = output[0]`));
      lines.push(I(`else:`));
      lines.push(I(`    result = output`));
      lines.push(``);
      lines.push(I(`boxes = result["boxes"]`));
      lines.push(I(`scores = result["scores"]`));
      lines.push(I(`labels = result["labels"]`));
      lines.push(I(`masks = result["masks"]`));
      lines.push(``);
      lines.push(I(`keep = scores > cfg.conf_threshold`));
      lines.push(I(`boxes, scores, labels, masks = boxes[keep], scores[keep], labels[keep], masks[keep]`));
      lines.push(``);
      lines.push(I(`print(f"Detected {len(boxes)} instances:")`));
      lines.push(I(`for score, label in zip(scores, labels):`));
      lines.push(I(`    cls_name = cfg.class_names[label.item()] if label.item() < len(cfg.class_names) else f"class_{label.item()}"`));
      lines.push(I(`    print(f"  {cls_name}: {score.item():.3f}")`));
      lines.push(``);
      lines.push(I(`fig, ax = plt.subplots(1, figsize=(12, 8))`));
      lines.push(I(`ax.imshow(image)`));
      lines.push(I(`colors = plt.cm.Set3(np.linspace(0, 1, max(len(boxes), 1)))`));
      lines.push(I(`for i, (mask, score, label) in enumerate(zip(masks, scores, labels)):`));
      lines.push(I(`    m = mask[0].cpu().numpy() > 0.5`));
      lines.push(I(`    colored = np.zeros((*m.shape, 4))`));
      lines.push(I(`    colored[m] = colors[i]`));
      lines.push(I(`    colored[m, 3] = 0.5`));
      lines.push(I(`    ax.imshow(colored)`));
      lines.push(I(`ax.set_axis_off()`));
      lines.push(I(`plt.tight_layout()`));
      lines.push(I(`plt.savefig("instance_result.png", dpi=150, bbox_inches="tight")`));
      lines.push(I(`print("Saved visualization to instance_result.png")`));
    }
  }

  // if __name__ == "__main__"
  lines.push(``);
  lines.push(``);
  lines.push(`# ── Entry Point ──`);
  lines.push(``);
  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    cfg = Config()`);
  lines.push(`    main(cfg)`);

  return lines.join("\n");
}

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <button class="inference-copy-btn" onClick={handleCopy}>
      {copied ? (
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="20 6 9 17 4 12" />
        </svg>
      ) : (
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
        </svg>
      )}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

const FORMAT_META = {
  torchscript: { ext: ".pt", label: "TorchScript", desc: "Portable TorchScript model for PyTorch inference" },
  onnx: { ext: ".onnx", label: "ONNX", desc: "Cross-platform model for ONNX Runtime, TensorRT, OpenVINO" },
  tensorrt: { ext: ".engine", label: "TensorRT", desc: "NVIDIA-optimized engine for maximum GPU inference speed" },
};

function DownloadModelButton({ runId, runName, project, exportFormat }) {
  const [status, setStatus] = useState("idle");
  const [error, setError] = useState("");

  // Reset status when format changes, but only if not actively downloading
  useEffect(() => {
    setStatus((prev) => (prev === "loading" ? prev : "idle"));
    setError("");
  }, [exportFormat]);

  const fmt = FORMAT_META[exportFormat] || FORMAT_META.torchscript;

  async function handleDownload() {
    if (!project) return;
    setStatus("loading");
    setError("");
    try {
      const sshCmd =
        project.connectionType === "remote" ? project.sshCommand : null;
      const taskClassMap = {
        Classification: "ImageClassifier",
        "Multi-Label Classification": "ImageClassifier",
        "Object Detection":
          project.detectionArch === "yolox" ? "YOLOXDetector" : "ObjectDetector",
        "Semantic Segmentation": "SemanticSegmentor",
        "Instance Segmentation": "InstanceSegmentor",
      };
      const taskClass = taskClassMap[project.taskType] || "ImageClassifier";
      await invoke("download_model", {
        projectPath: project.projectPath,
        runId,
        runName: runName || runId,
        taskClass,
        sshCommand: sshCmd,
        exportFormat: exportFormat || "torchscript",
      });
      setStatus("done");
      notify("Model Downloaded", `${fmt.label} model saved to ~/Downloads/${(runName || runId)}${fmt.ext}`);
    } catch (err) {
      setStatus("error");
      setError(String(err));
      notify("Download Failed", String(err));
    }
  }

  const icon =
    status === "loading" ? (
      <div class="download-spinner" />
    ) : status === "done" ? (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="20 6 9 17 4 12" />
      </svg>
    ) : (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
    );

  return (
    <div class="deploy-download-section">
      <div class="deploy-step-header">
        <svg class="deploy-step-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
        <div>
          <div class="deploy-step-title">Download {fmt.label} Model</div>
          <div class="deploy-step-desc">
            {fmt.desc}
          </div>
        </div>
      </div>
      <button
        class="deploy-download-btn"
        onClick={handleDownload}
        disabled={status === "loading"}
      >
        {icon}
        {status === "loading"
          ? "Converting & Downloading…"
          : status === "done"
            ? `Downloaded — ~/Downloads/${(runName || runId)}${fmt.ext}`
            : `Download Model (${fmt.ext})`}
      </button>
      {exportFormat === "tensorrt" && (
        <div class="deploy-step-desc" style={{ marginTop: "6px", fontSize: "11px" }}>
          Requires NVIDIA GPU and TensorRT installed on the target machine. The ONNX model is first exported, then converted to a TensorRT engine.
        </div>
      )}
      {error && (
        <div class="deploy-download-error">{error}</div>
      )}
    </div>
  );
}

export function InferenceTab({ run, project }) {
  const taskType = run.taskType || project?.taskType || "Classification";
  const backbone = run.backbone || run.model || "efficientnet_b0";
  const hp = { ...(run.hyperparameters || {}), ...(run.fileHparams || {}) };
  const defaultSize = hp.image_size || hp.imageSize || 224;
  const defaultClasses = hp.num_classes || hp.numClasses || project?.numClasses || 10;

  const isDetection = taskType === "Object Detection" || taskType === "Instance Segmentation";
  const isMultiLabel = taskType === "Multi-Label Classification";

  const [exportFormat, setExportFormat] = useState("torchscript");
  const extMap = { torchscript: ".pt", onnx: ".onnx", tensorrt: ".engine" };
  const ext = extMap[exportFormat] || ".pt";

  const [modelPath, setModelPath] = useState(`${(run.name || run.id)}${ext}`);
  const [imagePath, setImagePath] = useState("image.jpg");
  const [device, setDevice] = useState("cuda");
  const [imageSize, setImageSize] = useState(String(defaultSize));
  const [numClasses, setNumClasses] = useState(String(defaultClasses));
  const [confThreshold, setConfThreshold] = useState("0.5");
  const [classNames, setClassNames] = useState("");

  // Update model path extension when format changes
  function handleFormatChange(newFormat) {
    setExportFormat(newFormat);
    const newExt = extMap[newFormat] || ".pt";
    const baseName = modelPath.replace(/\.(pt|onnx|engine)$/, "");
    setModelPath(`${baseName}${newExt}`);
  }

  const script = generateInferenceScript({
    taskType,
    backbone,
    numClasses: numClasses || defaultClasses,
    imageSize: imageSize || defaultSize,
    modelPath,
    imagePath,
    device,
    confThreshold: parseFloat(confThreshold) || 0.5,
    classNames,
    exportFormat,
  });

  const highlighted = useMemo(() => highlightPython(script), [script]);

  return (
    <div class="inference-tab">
      {/* Top config area — collapsible, no scroll */}
      <div class="inference-config-area">
        {/* Format selector */}
        <div class="deploy-format-selector">
          <div class="deploy-step-header">
            <svg class="deploy-step-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12 2L2 7l10 5 10-5-10-5z" />
              <path d="M2 17l10 5 10-5" />
              <path d="M2 12l10 5 10-5" />
            </svg>
            <div>
              <div class="deploy-step-title">Export Format</div>
              <div class="deploy-step-desc">
                Choose the deployment format for your model
              </div>
            </div>
          </div>
          <div class="deploy-format-options">
            {[
              {
                id: "torchscript", label: "TorchScript", desc: "PyTorch native", icon: (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" />
                  </svg>
                )
              },
              {
                id: "onnx", label: "ONNX", desc: "Cross-platform", icon: (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx="12" cy="12" r="10" />
                    <path d="M8 12h8" />
                    <path d="M12 8v8" />
                  </svg>
                )
              },
              {
                id: "tensorrt", label: "TensorRT", desc: "NVIDIA optimized", icon: (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
                  </svg>
                )
              },
            ].map(f => (
              <button
                key={f.id}
                class={`deploy-format-btn${exportFormat === f.id ? " active" : ""}`}
                onClick={() => handleFormatChange(f.id)}
              >
                {f.icon}
                <div>
                  <div class="deploy-format-btn-label">{f.label}</div>
                  <div class="deploy-format-btn-desc">{f.desc}</div>
                </div>
              </button>
            ))}
          </div>
        </div>

        <DownloadModelButton runId={run.id} runName={run.name || run.id} project={project} exportFormat={exportFormat} />

        <div class="inference-params">
          <div class="deploy-step-header">
            <svg class="deploy-step-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="16 18 22 12 16 6" />
              <polyline points="8 6 2 12 8 18" />
            </svg>
            <div>
              <div class="deploy-step-title">Inference Script</div>
              <div class="deploy-step-desc">
                Configure parameters and copy the ready-to-run Python script
              </div>
            </div>
          </div>
          <div class="inference-params-grid">
            <label class="inference-field">
              <span>Model Path</span>
              <input type="text" value={modelPath} onInput={(e) => setModelPath(e.currentTarget.value)} placeholder={`best_model${ext}`} />
            </label>
            <label class="inference-field">
              <span>Image Path</span>
              <input type="text" value={imagePath} onInput={(e) => setImagePath(e.currentTarget.value)} placeholder="image.jpg" />
            </label>
            {exportFormat === "torchscript" && (
              <label class="inference-field">
                <span>Device</span>
                <select value={device} onChange={(e) => setDevice(e.currentTarget.value)}>
                  <option value="cuda">CUDA (GPU)</option>
                  <option value="cpu">CPU</option>
                  {platform.value === "macos" && <option value="mps">MPS (Apple Silicon)</option>}
                </select>
              </label>
            )}
            {exportFormat === "onnx" && (
              <label class="inference-field">
                <span>Provider</span>
                <select value={device} onChange={(e) => setDevice(e.currentTarget.value)}>
                  <option value="cuda">CUDA (GPU)</option>
                  <option value="cpu">CPU</option>
                  {platform.value === "macos" && <option value="mps">CoreML (Apple)</option>}
                  {platform.value === "windows" && <option value="directml">DirectML (Windows GPU)</option>}
                </select>
              </label>
            )}
            <label class="inference-field">
              <span>Image Size</span>
              <input type="number" value={imageSize} onInput={(e) => setImageSize(e.currentTarget.value)} min="32" max="1024" />
            </label>
            <label class="inference-field">
              <span>Num Classes</span>
              <input type="number" value={numClasses} onInput={(e) => setNumClasses(e.currentTarget.value)} min="2" />
            </label>
            {(isDetection || isMultiLabel) && (
              <label class="inference-field">
                <span>{isDetection ? "Confidence Threshold" : "Sigmoid Threshold"}</span>
                <input type="number" value={confThreshold} onInput={(e) => setConfThreshold(e.currentTarget.value)} min="0" max="1" step="0.05" />
              </label>
            )}
            <label class="inference-field inference-field-wide">
              <span>Class Names (comma-separated, optional)</span>
              <input type="text" value={classNames} onInput={(e) => setClassNames(e.currentTarget.value)} placeholder="cat, dog, bird, ..." />
            </label>
          </div>
        </div>
      </div>

      <div class="inference-script-container">
        <div class="inference-script-header">
          <span class="inference-script-filename">
            <svg class="python-logo" width="14" height="14" viewBox="0 0 256 255" style="flex-shrink:0">
              <path d="M126.916.072c-64.832 0-60.784 28.115-60.784 28.115l.072 29.128h61.868v8.745H41.631S.145 61.355.145 126.77c0 65.417 36.21 63.097 36.21 63.097h21.61v-30.356s-1.165-36.21 35.632-36.21h61.362s34.475.557 34.475-33.319V33.97S194.67.072 126.916.072zM92.802 19.66a11.12 11.12 0 0 1 11.13 11.13 11.12 11.12 0 0 1-11.13 11.13 11.12 11.12 0 0 1-11.13-11.13 11.12 11.12 0 0 1 11.13-11.13z" class="python-top" />
              <path d="M128.757 254.126c64.832 0 60.784-28.115 60.784-28.115l-.072-29.127H127.6v-8.745h86.441s41.486 4.705 41.486-60.712c0-65.416-36.21-63.096-36.21-63.096h-21.61v30.355s1.165 36.21-35.632 36.21h-61.362s-34.475-.557-34.475 33.32v56.013s-5.235 33.897 62.518 33.897zm34.114-19.586a11.12 11.12 0 0 1-11.13-11.13 11.12 11.12 0 0 1 11.13-11.131 11.12 11.12 0 0 1 11.13 11.13 11.12 11.12 0 0 1-11.13 11.13z" class="python-bottom" />
            </svg>
            inference.py
          </span>
          <CopyButton text={script} />
        </div>
        <pre class="inference-script-code"><code dangerouslySetInnerHTML={{ __html: highlighted }} /></pre>
      </div>
    </div>
  );
}
